# nginx.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: default
    namespace: spacex-argocd
spec:
    project: netflix
    source:
        repoURL: 'https://github.com/VaishnaviDeshmukh2002/DevSecOps-Project.git'
        path: Kubernetes
        targetRevision: main
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: vaish
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
